//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacunasAntiCovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoCiudadano
    {
        public int Id { get; set; }
        public int VacunaId { get; set; }
        public int CiudadanoId { get; set; }
        public int CentroDeAsistenciaId { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public bool Activo { get; set; }
        public int UsuarioAgregaId { get; set; }
        public System.DateTime FechaAgrega { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModificaId { get; set; }
    
        public virtual CentroDeAsistencia CentroDeAsistencia { get; set; }
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Vacuna Vacuna { get; set; }
    }
}
