//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacunasAntiCovid
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.CentroDeAsistencias = new HashSet<CentroDeAsistencia>();
            this.CentroDeAsistencias1 = new HashSet<CentroDeAsistencia>();
            this.Ciudadanoes = new HashSet<Ciudadano>();
            this.Ciudadanoes1 = new HashSet<Ciudadano>();
            this.DestinoVacunas = new HashSet<DestinoVacuna>();
            this.DestinoVacunas1 = new HashSet<DestinoVacuna>();
            this.HistoricoCiudadanoes = new HashSet<HistoricoCiudadano>();
            this.HistoricoCiudadanoes1 = new HashSet<HistoricoCiudadano>();
            this.Vacunas = new HashSet<Vacuna>();
            this.Vacunas1 = new HashSet<Vacuna>();
        }
    
        public int Id { get; set; }
        public string Usuario1 { get; set; }
        public byte[] Clave { get; set; }
        public string Correo { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> RolId { get; set; }
        public int UsuarioAgregaId { get; set; }
        public System.DateTime FechaAgrega { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModificaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroDeAsistencia> CentroDeAsistencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroDeAsistencia> CentroDeAsistencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ciudadano> Ciudadanoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ciudadano> Ciudadanoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinoVacuna> DestinoVacunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinoVacuna> DestinoVacunas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoCiudadano> HistoricoCiudadanoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricoCiudadano> HistoricoCiudadanoes1 { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacuna> Vacunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacuna> Vacunas1 { get; set; }
    }
}
